### ISSUE TITLE
Cursor pointer

### ISSUE THREAD

**Issue by kenzhemir** [Tauka/uniquora-front#3]
All the anchors(links) have an I-cursor, but it would be preferable to have and pointer cursor on them

**Comment by Tauka** [comment]
Thanks for reporting. I'm not sure I understood what you mean. Can you describe it with more details, and attach screenshot if possible?

**Comment by kenzhemir** [comment]
Cursor on links on my Firefox 51.0.1 for Ubuntu is shown as a I-cursor
![index](https://cloud.githubusercontent.com/assets/16799744/23589834/2e5740dc-01ff-11e7-80dd-ff0d5184cf43.png)
But by convention is usually pointer
![9cp6gxbyi](https://cloud.githubusercontent.com/assets/16799744/23589839/4037ccfe-01ff-11e7-9c4c-7e6bb99499ea.gif)

Example (cursor is on the Uniquora logo, which is link)
![screenshot from 2017-03-06 00-00-25](https://cloud.githubusercontent.com/assets/16799744/23589878/02f560c6-0200-11e7-8a4c-1bc12bd46fdc.png)

UPD: cannot capture the actual cursor(always shown default one) on the window by printscreent =(

The fix is smth like
a { cursor: pointer; }
.question-title { cursor: pointer; }

**Comment by Tauka** [comment]
Thanks for clarifying. Now I see, what you mean. If you know how to fix it, feel free to submit pull request, and I will merge =)

**Comment by Tauka** [comment]
If you are gonna submit PR, make sure you put CSS code regarding general tags/classes (e.g. `<a>`) in `global.scss`, and particular classes in corresponding file. Every css file corresponds to one page in "./page" in source code folders. For example, .question-title should be in `questionFeed.scss`, since it's actual markup written in "../components/questionFeed.js"
